apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-example
  labels:
    app: grpc-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-example
  template:
    metadata:
      labels:
        app: grpc-example
    spec:
      containers:
      - name: grpc-example
        image: yukirii/grpc-example:latest
        imagePullPolicy: Always
        command: ["/server"]
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
