apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gke-grpc-example
  labels:
    app: gke-grpc-example
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gke-grpc-example
    spec:
      containers:
      - name: gke-grpc-example
        image: shiftky/gke-grpc-example:730352e5
        imagePullPolicy: Always
        command: ["/server"]
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
